# Generated by Django 5.0.6 on 2024-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('Human Resources', 'Human Resources'), ('Sales', 'Sales'), ('Communication', 'Communication'), ('Finance Department', 'Finance Department'), ('Administration', 'Administration'), ('Development', 'Development'), ('Marketing', 'Marketing'), ('Research and development', 'Research and development'), ('Production department', 'Production department'), ('Technical Support', 'Technical Support')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(choices=[('CTO', 'CTO'), ('Software developer', 'Software developer'), ('Manager', 'Manager'), ('VP of Marketing', 'VP of Marketing'), ('Tech lead', 'Tech lead'), ('Computer engineer', 'Computer engineer'), ('CEO', 'CEO'), ('Director', 'Director'), ('Architect', 'Architect'), ('Product Manager', 'Product Manager')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Date', models.DateField()),
                ('Department', models.ManyToManyField(to='emp.departmentmodel')),
                ('Designation', models.ManyToManyField(to='emp.designationmodel')),
            ],
        ),
    ]
